[package]
name = "el-guacal-server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0.17"
async-graphql-axum = "7.0.17"
axum = "0.8.6"
chrono = {version = "0.4.42", features = ["clock"]}
tokio = {version = "1.48.0",  features = ["full"]}
uuid = { version = "1.17.0", features = ["v4"] }
